# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('golf_course', models.CharField(max_length=250)),
                ('entry_fee', models.IntegerField()),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
