# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20180628_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
