# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20190309_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='number_of_pools',
        ),
    ]
