# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_tournament_number_of_pools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
