# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerevent_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='total_score_to_par',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
