# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_number_of_pools'),
        ('players', '0004_auto_20180526_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
    ]
