# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_userevent_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerevent',
            name='round_four_to_par',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_one_to_par',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_three_to_par',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_two_to_par',
            field=models.IntegerField(blank=True),
        ),
    ]
