# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20180628_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='total_score_to_par',
            field=models.IntegerField(default=0),
        ),
    ]
