# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
