# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20181121_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerevent',
            name='round_four_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_one_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_three_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_two_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
