# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20181121_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='round_four_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='round_one_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='round_three_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='round_two_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
