# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20181127_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerevent',
            name='round_one_to_par',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
