# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20181127_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_four_to_par',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_three_to_par',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='round_two_to_par',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
