# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20181128_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
