# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20190308_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
