# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20190308_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerevent',
            name='pool',
        ),
    ]
