# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='players',
        ),
        migrations.AddField(
            model_name='pool',
            name='player_events',
            field=models.ManyToManyField(to='players.PlayerEvent'),
        ),
    ]
