# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20190309_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='player_events',
            new_name='players',
        ),
    ]
