# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20190309_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='players',
            field=models.ManyToManyField(to='players.Player'),
        ),
    ]
