# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20190309_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='player_events',
        ),
        migrations.AddField(
            model_name='userevent',
            name='players',
            field=models.ManyToManyField(to='players.Player'),
        ),
    ]
