# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20190309_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerevent',
            name='round_four_to_par',
        ),
        migrations.RemoveField(
            model_name='playerevent',
            name='round_one_to_par',
        ),
        migrations.RemoveField(
            model_name='playerevent',
            name='round_three_to_par',
        ),
        migrations.RemoveField(
            model_name='playerevent',
            name='round_two_to_par',
        ),
        migrations.AddField(
            model_name='playerevent',
            name='holes_played_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='round_four_total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='round_one_total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='round_three_total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='round_two_total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='todays_score_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='total_score_to_par',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
