# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20190310_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerevent',
            name='holes_played_today',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='todays_score_to_par',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerevent',
            name='total_score_to_par',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
