# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20190310_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='players.Player'),
        ),
    ]
